import Head from "next/head";
import { AiFillLinkedin } from "react-icons/ai";
import food from "../public/foodproject.jpg";
import nba from "../public/projectnba.jpg";
import weather from "../public/weatherapp.jpg";
import riga from "../public/autoskolariga.jpg";
import meme from "../public/meme.jpg";
import { BsInstagram } from "react-icons/bs";
import Cards from "./Cards";

import Image from "next/image";
import myimg from "../public/finalme-removebg-preview.png";
import { useState } from "react";

import { BsFillMoonStarsFill, BsGithub, BsCodeSquare } from "react-icons/bs";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Toms Freimanis Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between ">
            <h1 className=" text-l md:text-2xl font-burtons dark:text-white">
              Developer{" "}
              <span className="text-teal-600 font-extrabold ">TF</span>
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-4xl"
                />
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-6xl py-2 text-teal-600 font-medium md:text-6xl">
              Toms Freimanis
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-500 md:text-xl max-w-lg mx-auto">
              I design and code beautifully simple things. I enjoy creating
              things that live on the internet. My interest in web development
              started back in 2021 when I decided to try make a homepage for a
              friend.
            </p>
          </div>
          <div className="text-6xl flex justify-center gap-16 py-3 text-teal-600">
            <a
              href="https://www.linkedin.com/in/toms-freimanis-b96370235/"
              target="_blank"
            >
              {" "}
              <AiFillLinkedin className="hover:text-black dark:hover:text-black " />
            </a>
            <a href="https://www.instagram.com/bomisstudio/" target="_blank">
              {" "}
              <BsInstagram className="hover:text-black dark:hover:text-red-600" />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 mt-20 overflow-hidden">
            <Image src={myimg} layout="fill" objectFit="cover" alt="alt" />
          </div>
        </section>

        <Cards />
        <section>
          <div className="flex flex-col justify-center gap-10 py-10 lg:flex-row lg:flex-wrap">
            <h3 className="text-5xl py-1  dark:text-white">Portfolio</h3>
          </div>
          <div className="flex flex-col gap-20 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={food}
                className="rounded-lg object-cover shadow-md shadow-teal-600"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <div className="text-4xl flex justify-center gap-16 mt-4 py-2 text-teal-600  cursor-pointer ">
                <a
                  href="https://github.com/TomsFreimanis/project13"
                  target="_blank"
                >
                  <BsGithub className="hover:text-black dark:hover:text-white" />
                </a>
                <a href="#">
                  <BsCodeSquare className="hover:text-black dark:hover:text-white" />
                </a>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={weather}
                className="rounded-lg object-cover shadow-md shadow-teal-600"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <div className="text-4xl flex justify-center gap-16 mt-4 py-2 text-teal-600  cursor-pointer ">
                <a
                  href="https://github.com/TomsFreimanis/weather"
                  target="_blank"
                >
                  <BsGithub className="hover:text-black dark:hover:text-white" />
                </a>
                <a href="#">
                  <BsCodeSquare className="hover:text-black dark:hover:text-white" />
                </a>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={nba}
                className="rounded-lg object-cover shadow-md shadow-teal-600"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <div className="text-4xl flex justify-center gap-16 mt-4 py-2 text-teal-600  cursor-pointer ">
                <a href="https://github.com/TomsFreimanis/nba" target="_blank">
                  <BsGithub className="hover:text-black dark:hover:text-white" />
                </a>
                <a href="#">
                  <BsCodeSquare className="hover:text-black dark:hover:text-white" />
                </a>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={riga}
                className="rounded-lg object-cover shadow-md shadow-teal-600"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <div className="text-4xl flex justify-center gap-16 mt-4 py-2 text-teal-600  cursor-pointer ">
                <a href="#">
                  <BsGithub className="hover:text-black dark:hover:text-white" />
                </a>
                <a href="https://rigasautoskola.lv/" target="_blank">
                  <BsCodeSquare className="hover:text-black dark:hover:text-white" />
                </a>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={meme}
                className="rounded-lg object-cover shadow-md shadow-teal-600"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <div className="text-4xl flex justify-center gap-16 mt-4 py-2 text-teal-600  cursor-pointer ">
                <a
                  href="https://github.com/TomsFreimanis/memegenerator"
                  target="_blank"
                >
                  <BsGithub className="hover:text-black dark:hover:text-white" />
                </a>
                <a href="#">
                  <BsCodeSquare className="hover:text-black dark:hover:text-white" />
                </a>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={food}
                className="rounded-lg object-cover shadow-md shadow-teal-600"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <div className="text-4xl flex justify-center gap-16 mt-4 py-2 text-teal-600  cursor-pointer ">
                <a href="#">
                  <BsGithub className="hover:text-black dark:hover:text-white" />
                </a>
                <a href="#">
                  <BsCodeSquare className="hover:text-black dark:hover:text-white" />
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
